Refactor component to use new token structure
selsa-inube/inubekit-tag pull request #2
Opened 2024-03-07 22:22 UTC by JanuarAsprilla

the `tag `component has been refactored to use the new token structure offered by `foundations `as well as the new version of `text`

2024-03-12 03:34 UTC, wfercanas requested changes

2024-03-12 03:34 UTC, wfercanas commented on src/Tag/index.tsx
We're using the components defined in the V2 file of the design-system project in figma.
As you can see there, we have two types of tags:

![image](https://github.com/selsa-inube/inubekit-tag/assets/36939686/927a284e-8b9a-41b1-8692-e8287172e4d3)

1. There are those with a background color that is very intense and the text is just a contrast color.
2. There are some others whose background is less intense and the text uses the same range of color as the background but with more intensity.

This shouldn't be a surprise, since the token table for this component adds a column named `weight` to differenciate the first group of tags from the second:

![image](https://github.com/selsa-inube/inubekit-tag/assets/36939686/cac742d1-d806-4633-adec-cdc6151d0c30)

So, the last time I returned this task was because the development of this component doesn't cover the whole variants in the figma file.

**Refactor the component to allow it to support the weight prop and use the new token structure to support the different variants.**

2024-03-12 21:09 UTC, JanuarAsprilla commented on src/Tag/index.tsx
solved

2024-03-13 16:17 UTC, JanuarAsprilla commented on src/Tag/props.ts
> +const weight = ["normal", "strong"] as const;
solved

2024-03-13 16:28 UTC, JanuarAsprilla commented on src/Tag/styles.js
> +    (theme?.tag?.[$appearance]?.[$weight]?.background?.color && black) ||
solved

2024-03-13 16:30 UTC, JanuarAsprilla commented on vite.config.ts
> +      external: ["react", "ract-dom", "styled-components", "react/jsx-runtime", "inubekit/foundations", "inubekit/text"],
solved

2024-03-13 16:31 UTC, JanuarAsprilla commented on vite.config.ts
> +      external: ["react", "ract-dom", "styled-components", "react/jsx-runtime", "inubekit/foundations", "inubekit/text"],
solved

2024-03-14 14:52 UTC, wfercanas commented on src/Tag/props.ts
> +const weight = ["normal", "strong"] as const;
The one that should be in plural is the array, not the type.

You have an appearances array, and with that array you create the Appearance type. The same applies to Weight: the array should be named weights and the type should be name Weight.

2024-03-14 15:27 UTC, JanuarAsprilla commented on src/Tag/props.ts
> +const weight = ["normal", "strong"] as const;
solved

2024-03-14 16:55 UTC, wfercanas requested changes

2024-03-14 16:55 UTC, wfercanas commented on src/Tag/index.tsx
>  const darkTextAppearances = ["warning", "gray", "light"];
This array isn't necessary because now the tokens provide the value directly.

If the tag is of weight strong, then the background.color token indicates how strong the background is and the content.color indicates if the text goes light or dark.

You don't have to hardcode that information here, just use the values that are received from the tokens.

2024-03-14 16:55 UTC, wfercanas commented on src/Tag/index.tsx
> +const getTextAppearance = (
This function also should be deleted. Just use the information that comes through the tokens.

2024-03-14 16:55 UTC, wfercanas commented on src/Tag/index.tsx
> +  weight: Weight;
Weight here is defined as a mandatory prop. The developer should always decide which weight to use.
We can turn this prop into an optional one and define "regular" as the default value.

2024-03-18 17:48 UTC, JanuarAsprilla commented on src/Tag/index.tsx
> +  weight?: "regular" | "strong";
solved

2024-03-18 17:48 UTC, JanuarAsprilla commented on src/Tag/index.tsx
> +  weight: Weight;
solved

2024-03-18 17:48 UTC, JanuarAsprilla commented on src/Tag/index.tsx
> +const getTextAppearance = (
solved

2024-03-18 17:48 UTC, JanuarAsprilla commented on src/Tag/index.tsx
>  const darkTextAppearances = ["warning", "gray", "light"];
solved

2024-03-18 19:18 UTC, cmarin001 requested changes

2024-03-18 19:18 UTC, cmarin001 commented on src/Tag/index.tsx
> +  const { appearance, weight, label } = props;
what should be the default value for weight?

2024-03-18 19:45 UTC, JanuarAsprilla commented on src/Tag/index.tsx
> +  const { appearance, weight, label } = props;
solved

2024-03-19 16:59 UTC, wfercanas requested changes

2024-03-19 16:59 UTC, wfercanas commented on src/Tag/index.tsx
> +          weight === "normal"
This ternary is not necessary. Since you have the value in `weight` prop, the assignment to appearance prop could be:
`appearance={inube.tag[appearance][weight].content}`

2024-03-19 16:59 UTC, wfercanas commented on src/Tag/index.tsx
> +                .apparence as keyof typeof inube.tag)
The last part of the token cannot be named "apparance", that is a typo.

Process the card in jira to adjust the token structure, and then install here the new version of foundations to adjust this partl.

2024-03-19 16:59 UTC, wfercanas commented on src/Tag/styles.js
> +    $weight === "strong"
This ternary isn't required, use `inube.tag[$appearance][$weight].background.color`

2024-03-19 21:06 UTC, JanuarAsprilla commented on src/Tag/styles.js
> +    $weight === "strong"
solved

2024-03-21 20:00 UTC, JanuarAsprilla commented on src/Tag/index.tsx
> +                .apparence as keyof typeof inube.tag)
solved

2024-03-27 15:41 UTC, wfercanas approved these changes

2024-04-01 15:25 UTC, wfercanas approved these changes

2024-04-01 15:25 UTC, merged